#!/usr/bin/env python3

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read(path):
    return (ROOT / path).read_text(encoding="utf-8")


def require(condition, message):
    if not condition:
        raise AssertionError(message)


def main():
    root = ROOT.parent
    algorithm = read("agent_target_dqn/algorithm/algorithm.py")
    agent = read("agent_target_dqn/agent.py")
    conf = read("agent_target_dqn/conf/conf.py")
    definition = read("agent_target_dqn/feature/definition.py")
    model = read("agent_target_dqn/model/model.py")
    preprocessor = read("agent_target_dqn/feature/preprocessor.py")
    traffic_utils = read("agent_target_dqn/feature/traffic_utils.py")
    workflow = read("agent_target_dqn/workflow/train_workflow.py")
    agent_entrypoints = [
        ("agent_target_dqn/agent.py", agent),
        ("agent_dqn/agent.py", read("agent_dqn/agent.py")),
        ("agent_ppo/agent.py", read("agent_ppo/agent.py")),
        ("agent_diy/agent.py", read("agent_diy/agent.py")),
    ]
    package_script = root / "scripts" / "package_submission.sh"
    check_script = root / "scripts" / "check_offline.sh"

    require(
        "DIM_OF_OBSERVATION = 638" in conf,
        "observation dim should include 560 grid + 8 phase + 4 age + 8 traffic + 8 trend + 8 history + 42 lane stats",
    )
    require("PHASE_FEATURE_DIM = 8" in conf, "phase feature dimension should stay explicit")
    require("PHASE_AGE_FEATURE_DIM = 4" in conf, "phase age feature dimension should stay explicit")
    require("TRAFFIC_FEATURE_DIM = 8" in conf, "traffic feature dimension should stay explicit")
    require("TRAFFIC_TREND_FEATURE_DIM = 8" in conf, "traffic trend feature dimension should stay explicit")
    require("TRAFFIC_HISTORY_FEATURE_DIM = 8" in conf, "traffic history feature dimension should stay explicit")
    require("TRAFFIC_HISTORY_SIZE = 4" in conf, "traffic history window should stay explicit")
    require("LANE_STAT_FEATURE_DIM = 42" in conf, "lane stat feature dimension should stay explicit")
    require("DIM_OF_ACTION = DIM_OF_ACTION_PHASE * DIM_OF_ACTION_DURATION" in conf, "joint action dimension should be explicit")
    require("NUMB_HEAD = 1" in conf, "Target-DQN should use one joint action Q head")
    require("FAIRNESS_BONUS_SCALE" in conf, "fairness reward scale should stay explicit")
    require("REWARD_DELAY_CAP" in conf, "reward delay penalty should stay bounded")
    require("REWARD_CLIP" in conf, "reward values should stay clipped for DQN stability")
    require("DURATION_STEP" in conf, "duration bins should cover the configured green duration range")
    require("def duration_index_to_seconds" in conf, "duration index to seconds mapping should be centralized")
    require("def duration_seconds_to_index" in conf, "duration seconds to index mapping should be centralized")
    require("action_shape = [Config.DIM_OF_ACTION]" in model, "model should output one joint action Q head")
    require("def _prepare_input" in model, "model should normalize input tensor shape")
    require("s.unsqueeze(0)" in model, "model should batch one-dimensional observations")
    require("F.pad(s" in model, "model should pad short observation vectors")
    require("s[:, : Config.DIM_OF_OBSERVATION]" in model, "model should truncate long observation vectors")
    require("torch.nan_to_num(s" in model, "model should sanitize non-finite input tensors")
    require("def _as_numpy_array" in model, "model should tolerate ragged Python observation batches")
    require("except Exception:" in model, "model should isolate unexpected numpy conversion failures")
    require("np.stack(rows)" in model, "model should stack normalized ragged rows")
    require("def _fit_numpy_width" in model, "model should normalize ragged row width before tensor conversion")
    for agent_path, agent_source in agent_entrypoints:
        require("def _configure_torch_threads" in agent_source, f"{agent_path} should guard torch thread setup")
        require("\n_configure_torch_threads()\n" in agent_source, f"{agent_path} should call guarded torch thread setup")
        require("except RuntimeError" in agent_source, f"{agent_path} should tolerate torch thread setup RuntimeError")

    require("target_model = self.model" not in algorithm, "target model must not alias online model")
    require("deepcopy(self.model)" in algorithm, "target model should be an independent copy")
    require("def update_target_q" in algorithm, "target network sync method is required")
    require("online_next_outputs" in algorithm, "Double DQN should select next action with online network")
    require("next_q_value = target_outputs" in algorithm, "target network should evaluate selected next action")
    require("smooth_l1_loss" in algorithm, "TD loss should use Huber loss for stability")
    require("_action_to_joint_index" in algorithm, "training must map env action to joint Q index")
    require("Config.DURATION_STEP" in algorithm, "training should invert binned duration seconds to action indices")
    require("def _phase_legal_mask" in algorithm, "training should normalize legal phase masks")
    require("def _joint_legal_mask" in algorithm, "training should expand phase legality to joint actions")
    require("joint_legal_mask" in algorithm, "Double DQN joint target should use legal action mask")
    require("total_reward = rew.sum" in algorithm, "joint Q target should train on total reward")
    require("Config.MIN_GREEN_DURATION" in algorithm, "duration seconds must be converted to duration index")
    require("def _sample_batch" in algorithm, "learn should normalize sample batch containers")
    require("list_sample_data = self._sample_batch(list_sample_data)" in algorithm, "learn should materialize batches safely")
    require("if not list_sample_data" in algorithm, "learn should handle empty batches")
    require("sample batch iteration failed" in algorithm, "learn should log malformed batch containers")
    require("def _sample_field" in algorithm, "learn should isolate malformed sample attributes")
    require('self._sample_field(frame, "obs", [])' in algorithm, "learn should use safe obs field reads")
    require('"act",' in algorithm and "[0, 0, Config.MIN_GREEN_DURATION]" in algorithm, "learn should use safe action field reads")
    require('"legal_action",' in algorithm and "[1] * Config.DIM_OF_ACTION_PHASE" in algorithm, "learn should use safe legal action field reads")
    require("def _normalize_tensor" in algorithm, "learn should normalize malformed sample tensors")
    require("except Exception:" in algorithm, "learn should isolate unexpected sample tensor conversion failures")
    require("F.pad(tensor" in algorithm, "learn should pad short sample tensors")
    require("tensor = tensor[:width]" in algorithm, "learn should truncate long sample tensors")
    require("width=Config.DIM_OF_OBSERVATION" in algorithm, "learn should normalize observation width before stacking")
    require("width=Config.DIM_OF_ACTION_PHASE" in algorithm, "learn should normalize legal action width before stacking")
    require("def _finite_tensor" in algorithm, "learn should sanitize non-finite tensors")
    require("obs = self._finite_tensor(obs)" in algorithm, "learn should sanitize observations")
    require("rew = self._finite_tensor(rew)" in algorithm, "learn should sanitize rewards")
    require("legal_action = self._finite_tensor(legal_action)" in algorithm, "learn should sanitize legal action masks")
    require("q_targets = self._finite_tensor(q_targets)" in algorithm, "learn should sanitize TD targets")
    require("torch.isfinite(loss)" in algorithm, "learn should skip optimizer steps on non-finite loss")
    require("non-finite loss" in algorithm, "learn should log non-finite loss skips")
    require("math.isfinite(model_grad_norm)" in algorithm, "learn should skip optimizer steps on non-finite gradients")
    require("non-finite grad norm" in algorithm, "learn should log non-finite gradient skips")
    require("def _put_monitor_data" in algorithm, "learn monitor reporting should be isolated")
    require("monitor.put_data" in algorithm, "learn should still report monitor data when available")
    require("monitor put_data failed" in algorithm, "learn should log monitor reporting failures")
    require("def _log_info" in algorithm, "learn logger calls should be isolated")
    require("except Exception" in algorithm, "learn monitor/logger helpers should tolerate backend failures")

    require('act=3' in definition, "SampleData.act should match [junction, phase, duration_seconds]")
    require("return 0, 0" not in definition, "reward_shaping must not return all-zero rewards")
    require("get_phase_pressure" in definition, "reward should use shared phase pressure")
    require("if not list_game_data" in definition, "sample_process should handle empty trajectories")
    require("if not sample_datas" in definition, "sample_process should handle all-invalid trajectories")
    require("def _safe_getattr" in definition, "sample_process should isolate malformed frame attributes")
    require("def _fixed_float_list" in definition, "sample_process should normalize sample field widths")
    require("except Exception:" in definition, "sample_process should isolate unexpected field conversion failures")
    require("np.nan_to_num(values" in definition, "sample_process should sanitize non-finite sample fields")
    require("def _max_action_duration" in definition, "sample action and reward duration caps should share model action range")
    require("_fixed_float_list(obs, Config.DIM_OF_OBSERVATION)" in definition, "sample_process should normalize obs width")
    require("_fixed_action_list(act)" in definition, "sample_process should normalize action width and bounds")
    require("_not_done_flag" in definition, "sample_process should normalize done flags")
    require('"true", "1", "yes", "y"' in definition, "sample_process should parse string true done flags")
    require('"false", "0", "no", "n", ""' in definition, "sample_process should parse string false done flags")
    require('reward = _safe_getattr(data, "rew", None)' in definition, "sample_process should handle missing rewards")
    require("sample_datas[i].legal_action = sample_datas[i + 1].legal_action" in definition, "samples should carry next-state phase legality")
    require("def _safe_int" in definition, "reward should sanitize scalar integer fields")
    require("def _clip_reward" in definition, "reward should clip malformed or oversized values")
    require("Config.REWARD_DELAY_CAP" in definition, "reward should cap extreme delay penalties")
    require("Config.REWARD_CLIP" in definition, "reward clipping should use config")
    require("except (TypeError, ValueError, IndexError, OverflowError)" in definition, "reward should catch overflow in malformed actions")
    require("frame_no = _safe_int" in definition, "reward should sanitize frame_no")
    require("_max_action_duration()" in definition, "reward duration targets should stay within model action range")
    require("_safe_int(served_frame" in definition, "fairness reward should sanitize phase service history")
    require('frame_state = _obs.get("frame_state")' in definition, "reward should tolerate missing frame_state")
    require('frame_state.get("vehicles", [])' in definition, "reward should tolerate missing vehicles")
    require("vehicles = [vehicle for vehicle in vehicles if isinstance(vehicle, dict)]" in definition, "reward should skip malformed vehicles")
    require("phase_index = int(np.clip(int(act[1])" in definition, "reward should clamp malformed phase actions")
    require("def _fairness_reward" in definition, "reward should include phase fairness term")
    require("def _mark_phase_served" in definition, "reward should update phase service bookkeeping")

    require("def _obs_batch" in agent, "predict should normalize observation batches")
    require("list_obs_data = self._obs_batch(list_obs_data)" in agent, "predict should materialize observation batches safely")
    require("predict observation batch failed" in agent, "predict should log malformed observation batch containers")
    require("def _obs_data_field" in agent, "predict should isolate malformed ObsData attributes")
    require('self._obs_data_field(obs_data, "legal_action")' in agent, "predict should default missing legal_action")
    require("Config.duration_index_to_seconds(duration_index)" in agent, "action_process must map duration index to seconds")
    require("def _safe_action_index" in agent, "action_process should sanitize action indices")
    require("junction_id = 0" in agent, "action_process should force single-junction actions")
    require("np.isfinite(value)" in agent, "action_process should reject NaN/Inf indices")
    require("def _safe_mapping_get" in agent, "agent should isolate mapping field reads")
    require("observation.get(" not in agent, "exploit should not directly read dict-like observation")
    require("raw_obs.get(" not in agent, "agent should not directly read dict-like raw observations")
    require("def _safe_float" in agent, "agent observation helpers should sanitize scalar values")
    require("def _safe_int" in agent, "agent observation helpers should sanitize frame numbers")
    require("duration = _safe_nonnegative_float" in agent, "phase features should sanitize duration")
    require("frame_no = _safe_int" in agent, "phase age should sanitize frame_no")
    require("not isinstance(last_served, list)" in agent, "phase age should reset malformed service history")
    require("phase_id = self._safe_action_index" in agent, "phase features should sanitize phase ids")
    require("def _phase_feature" in agent, "observation should include traffic signal phase features")
    require("def _phase_age_feature" in agent, "observation should include phase service age features")
    require("def _traffic_feature" in agent, "observation should include traffic pressure features")
    require("def _traffic_trend_feature" in agent, "observation should include traffic trend features")
    require("def _traffic_history_feature" in agent, "observation should include traffic history features")
    require("def _lane_stat_feature" in agent, "observation should include per-lane statistics")
    require("def _sanitize_observation" in agent, "observation should sanitize final feature vectors")
    require("observation = self._sanitize_observation(observation)" in agent, "observation should run final feature sanitation")
    require("np.nan_to_num(values" in agent, "observation sanitation should remove non-finite values")
    require("Config.DIM_OF_OBSERVATION" in agent, "observation sanitation should enforce configured width")
    require(
        "+ traffic_history_feature" in agent and "+ lane_stat_feature" in agent,
        "observation should append phase, phase-age, traffic, trend, history, and lane-stat features",
    )
    require(
        'raw_obs = _safe_mapping_get(observation, "obs", observation)' in agent,
        "exploit should tolerate missing or malformed obs wrapper",
    )
    require('frame_state = _safe_mapping_get(raw_obs, "frame_state", {})' in agent, "observation should tolerate missing frame_state")
    require('_safe_mapping_get(frame_state, "vehicles", [])' in agent, "observation should tolerate missing vehicles")
    require("traffic info update failed" in agent, "observation should isolate preprocess update failures")
    require(
        "vehicles = [vehicle for vehicle in vehicles if isinstance(vehicle, dict)]" in agent,
        "observation should filter malformed vehicle records",
    )
    require("def rule_based_action" in agent, "exploit should have a rule-based fallback")
    require("def _joint_action_mask" in agent, "prediction should expand phase legality to joint actions")
    require("if not mask.any()" in agent and "mask[:] = True" in agent, "prediction should recover empty phase masks")
    require(
        "empty_rows = ~joint_masks.any(axis=1)" in agent and "joint_masks[empty_rows, :] = True" in agent,
        "prediction should recover empty joint mask rows",
    )
    require("list_joint_action" in agent, "prediction should select joint actions")
    require("if not exploit_flag" in agent, "exploit should not decay training epsilon")
    require("if exploit_flag or np.random.rand() >= self._eps" in agent, "exploit should force greedy prediction")
    require("def _log_info" in agent, "agent info logger calls should be isolated")
    require("def _log_error" in agent, "agent error logger calls should be isolated")
    require("self._log_error(f\"exploit fallback" in agent, "exploit fallback logging should not raise")
    require("def _safe_rule_based_action" in agent, "exploit should isolate rule-based fallback failures")
    require("rule_based_action failed, use default action" in agent, "exploit should log final default fallback")
    require("self._log_error(f\"learn failed" in agent, "agent learn failures should be logged without raising")
    require("return self.algorithm.learn(list_sample_data)" in agent, "agent learn should still delegate to algorithm")
    require("self._log_info(f\"save model" in agent, "save_model success logging should not raise")
    require("self._log_info(f\"skip load model" in agent, "load_model skip logging should not raise")
    require(agent.count("self.logger.info(") == 1, "agent should route logger.info through one helper")
    require(agent.count("self.logger.error(") == 1, "agent should route logger.error through one helper")
    require("model_tmp_path" in agent, "save_model should write checkpoint through a temporary file")
    require("os.replace(model_tmp_path, model_file_path)" in agent, "save_model should atomically publish checkpoints")
    require("os.remove(model_tmp_path)" in agent, "save_model should clean temporary checkpoint files on failure")
    require("if not os.path.exists(model_file_path)" in agent, "load_model should handle missing latest model")
    require("unreadable checkpoint" in agent, "load_model should skip unreadable latest checkpoints")
    require("invalid checkpoint" in agent, "load_model should skip invalid latest checkpoint payloads")
    require(
        "except (RuntimeError, TypeError, ValueError) as err" in agent,
        "load_model should handle incompatible latest checkpoints",
    )
    require("incompatible checkpoint" in agent, "load_model should log incompatible latest checkpoints")
    require("self.algorithm.update_target_q()" in agent, "load_model should sync target network")

    require("def get_phase_pressure" in traffic_utils, "shared phase pressure helper is required")
    require("def get_lane_statistics" in traffic_utils, "shared lane statistics helper is required")
    require("def get_traffic_summary" in traffic_utils, "shared traffic summary helper is required")
    require("def get_traffic_trend" in traffic_utils, "shared traffic trend helper is required")
    require("def get_traffic_history_feature" in traffic_utils, "shared traffic history helper is required")
    require("get_lane_position_meters" in traffic_utils, "lane coordinate normalization helper is required")
    require("def _finite_float" in traffic_utils, "traffic helpers should sanitize scalar values")
    require("def _nonnegative_float" in traffic_utils, "traffic helpers should clamp non-negative traffic metrics")
    require("def _phase_array" in traffic_utils, "traffic helpers should normalize phase arrays")
    require("def vehicle_value" in traffic_utils, "traffic helpers should tolerate missing vehicle mapping fields")
    require('target_junction = vehicle_value(vehicle, "target_junction", 0)' in traffic_utils, "enter-lane checks should not require target_junction")
    require("def _default_target_junction" in preprocessor, "waiting-time helpers should default missing target_junction safely")
    require("def _waiting_target_junction" in preprocessor, "waiting-time helpers should not count malformed targetless vehicles")
    require("if not np.isfinite(y_pos)" in traffic_utils, "lane position helper should reject non-finite positions")
    require("except Exception:" in traffic_utils, "traffic helpers should isolate unexpected array conversion failures")
    require("np.nan_to_num(values" in traffic_utils, "legal action normalizer should sanitize non-finite values")
    require("np.nan_to_num(array" in traffic_utils, "traffic helper arrays should sanitize non-finite values")
    require(
        "except (KeyError, TypeError, ValueError, AttributeError)" in traffic_utils,
        "traffic helpers should skip malformed vehicle records",
    )
    require("def normalize_phase_legal_action" in traffic_utils, "phase legal action normalizer is required")
    require("last_traffic_summary = None" in preprocessor, "traffic trend state should reset each episode")
    require("traffic_history = []" in preprocessor, "traffic history state should reset each episode")
    require("phase_last_served_frame" in preprocessor, "phase service state should reset each episode")
    require("def _safe_float" in preprocessor, "traffic preprocessor should sanitize scalar frame values")
    require("def _safe_int" in preprocessor, "traffic preprocessor should sanitize frame numbers")
    require("def _is_hashable" in preprocessor, "traffic preprocessor should skip unhashable ids")
    require("def _safe_position_pair" in preprocessor, "traffic preprocessor should sanitize vehicle positions")
    require('start_info.get("junctions", [])' in preprocessor, "road init should tolerate partial init_state")
    require('frame_state = raw_obs.get("frame_state")' in preprocessor, "traffic update should tolerate missing frame_state")
    require('frame_state.get("vehicles", [])' in preprocessor, "traffic update should tolerate missing vehicles")
    require("frame_no = _safe_int" in preprocessor, "traffic update should sanitize frame_no")
    require("frame_time = _safe_float" in preprocessor, "traffic update should sanitize frame_time")
    require("vehicles = vehicles if isinstance(vehicles, list) else []" in preprocessor, "waiting helpers should tolerate non-list vehicles")
    require('vehicle_id = vehicle.get("v_id")' in preprocessor, "traffic update should skip malformed vehicles")
    require("not _is_hashable(vehicle_id)" in preprocessor, "traffic update should skip unhashable vehicle ids")
    require("except (KeyError, TypeError, ValueError, AttributeError, OverflowError)" in preprocessor, "traffic update should skip malformed dynamic fields")
    require("masked_fill" in agent, "joint Q-values should be masked before greedy selection")
    require("np.flatnonzero" in agent, "random exploration should sample only legal phase actions")

    require("phase_reward" in workflow and "duration_reward" in workflow, "workflow should monitor reward components")
    require("env_score" in workflow and "avg_delay" in workflow, "workflow should monitor platform score components")
    require("ENV_SCORE_ALIASES" in workflow, "workflow platform score aliases should be centralized")
    require("def _default_env_metric_snapshot" in workflow, "workflow should initialize score metric snapshots")
    require("def _env_score_metrics" in workflow, "workflow should extract platform score metrics safely")
    require("def _update_env_metric_snapshot" in workflow, "workflow should update score metric snapshots safely")
    require(
        "_update_env_metric_snapshot(env_metric_snapshot, env_reward, env_obs)" in workflow,
        "workflow should update platform score metrics after env.step",
    )
    require("score_info" in workflow and "scoreInfo" in workflow, "workflow should inspect common score info containers")
    require("def _optional_finite_float" in workflow, "workflow score metrics should reject non-finite values")
    require("def _shape_reward" in workflow, "workflow reward shaping should be isolated")
    require("_shape_reward(obs, last_predict_act, agent, logger)" in workflow, "workflow should shape intermediate rewards through helper")
    require("_shape_reward(_obs, last_predict_act, agent, logger)" in workflow, "workflow should shape terminal rewards through helper")
    require("reward shaping failed" in workflow, "workflow should log reward shaping failures")
    require("def _process_observation" in workflow, "workflow observation processing should be isolated")
    require("_process_observation(agent, obs, extra_info, logger)" in workflow, "workflow should process observations through the safe helper")
    require("observation process failed" in workflow, "workflow should log observation processing failures")
    require("def _update_traffic_info" in workflow, "workflow traffic info updates should be isolated")
    require("_update_traffic_info(agent, obs, extra_info, logger)" in workflow, "workflow should update non-decision traffic info through helper")
    require("traffic info update failed" in workflow, "workflow should log traffic update failures")
    require("def _obs_feature" in workflow, "workflow sampled frame feature extraction should be isolated")
    require("obs=_obs_feature(obs_data)" in workflow, "workflow should use fallback features when observation processing fails")
    require("observation process returned empty" in workflow, "workflow should fallback to rule policy when observation processing returns empty")
    require("def _read_usr_conf" in workflow, "workflow user config reading should be isolated")
    require("_read_usr_conf(\"agent_target_dqn/conf/train_env_conf.toml\", logger)" in workflow, "workflow should read user config through the safe helper")
    require("read usr conf failed" in workflow, "workflow should log user config read failures")
    require("def _handle_disaster_recovery" in workflow, "workflow disaster recovery helper should be isolated")
    require("_handle_disaster_recovery(env_obs, logger)" in workflow, "workflow should call disaster recovery through the safe helper")
    require("handle disaster recovery failed" in workflow, "workflow should log disaster recovery helper failures")
    require("def _reset_agent" in workflow, "workflow agent reset should be isolated")
    require("_reset_agent(agent, env_obs, logger)" in workflow, "workflow should reset agents through the safe helper")
    require("agent reset failed" in workflow, "workflow should log agent reset failures")
    require("def _need_to_predict" in workflow, "workflow should normalize legal_action before prediction gating")
    require("def _finite_float" in workflow, "workflow reward monitor should sanitize non-finite rewards")
    require("except (TypeError, ValueError, OverflowError)" in workflow, "workflow finite float helper should catch malformed scalars")
    require("math.isfinite" in workflow, "workflow reward monitor should reject NaN/Inf values")
    require("def _sample_batch_stats" in workflow, "workflow sample reward aggregation should be isolated")
    require("_sample_batch_stats(g_data, logger)" in workflow, "workflow should aggregate sample batch stats through the safe helper")
    require("sample reward read failed" in workflow, "workflow should log sample reward read failures")
    require("sample batch length failed" in workflow, "workflow should log malformed sample batch lengths")
    require("def _get_training_metrics" in workflow, "workflow training metrics fetch should be isolated")
    require("_get_training_metrics(logger)" in workflow, "workflow should fetch training metrics through the safe helper")
    require("get training metrics failed" in workflow, "workflow should log training metrics fetch failures")
    require("def _safe_env_value" in workflow, "workflow env mapping reads should be centralized")
    require("return env_obs.get(key, default)" in workflow, "workflow should still read normal env mappings")
    require('return int(_finite_float(_safe_env_value(env_obs, "frame_no", 0)))' in workflow, "workflow frame_no should use finite scalar sanitation")
    require("def _safe_done_flag" in workflow, "workflow done flags should be sanitized")
    require('normalized in ("true", "1", "yes", "y")' in workflow, "workflow should parse true string done flags")
    require('normalized in ("false", "0", "no", "n", "")' in workflow, "workflow should parse false string done flags")
    require("return value != 0.0" in workflow, "workflow should parse numeric done flags")
    require("def _safe_observation" in workflow, "workflow should tolerate missing observation payloads")
    require("def _safe_extra_info" in workflow, "workflow should tolerate missing extra_info payloads")
    require("def _safe_legal_action" in workflow, "workflow should tolerate missing legal_action in sampled frames")
    require('return _safe_env_value(obs, "legal_action", None)' in workflow, "workflow legal_action reads should be isolated")
    require("def _put_monitor_data" in workflow, "workflow monitor reporting should be isolated")
    require("monitor.put_data" in workflow, "workflow should still report monitor data when available")
    require("monitor put_data failed" in workflow, "workflow should log monitor reporting failures")
    require("try:" in workflow and "except Exception" in workflow, "workflow logger/monitor helpers should tolerate backend failures")
    require("def _normalize_reset_result" in workflow, "workflow should normalize tuple reset results")
    require("def _normalize_step_result" in workflow, "workflow should normalize tuple step results")
    require("len(step_result) >= 6" in workflow, "workflow should support documented six-item env.step results")
    require("len(step_result) == 5" in workflow, "workflow should support Gymnasium-style env.step results")
    require("len(step_result) == 4" in workflow, "workflow should support Gym-style env.step results")
    require("def _reset_env" in workflow, "workflow env reset should be isolated")
    require("_reset_env(env, usr_conf, logger)" in workflow, "workflow should reset environments through the safe helper")
    require("env reset failed" in workflow, "workflow should log env reset failures")
    require("def _step_env" in workflow, "workflow env step should be isolated")
    require("_step_env(env, act, logger)" in workflow, "workflow should step environments through the safe helper")
    require("env step failed" in workflow, "workflow should log env step failures")
    require('obs = _safe_observation(env_obs)' in workflow, "workflow reset path should use safe observation extraction")
    require('legal_action=_safe_legal_action(obs)' in workflow, "workflow sampled frame should use safe legal_action extraction")
    require('obs["legal_action"][0]' not in workflow, "workflow should not assume legal_action is always a list")
    require('obs["legal_action"]' not in workflow, "workflow should not directly index legal_action")
    require("_need_to_predict(obs)" in workflow, "workflow should use the robust prediction gate")
    require("def _safe_action" in workflow, "workflow final actions should be sanitized before env.step")
    require("act = _safe_action(act, need_to_predict, logger)" in workflow, "workflow should sanitize actions before stepping")
    require("invalid action, use default action" in workflow, "workflow should log invalid action fallbacks")
    require("Config.max_action_duration()" in workflow, "workflow action duration should stay within model action space")
    require("def _predict_action" in workflow, "workflow should centralize robust prediction fallback")
    require("predict returned empty action" in workflow, "workflow should log empty predictions")
    require("fallback to rule_based_action" in workflow, "workflow should fall back when prediction fails")
    require("[0, 0, Config.MIN_GREEN_DURATION]" in workflow, "workflow should have a final legal default action")
    require("run_episodes error: {e}" in workflow, "workflow should log the original episode exception")
    require("from e" in workflow, "workflow should preserve exception cause for platform debugging")
    require("def _load_latest_model" in workflow, "workflow latest loading should be isolated")
    require("_load_latest_model(agent, logger)" in workflow, "workflow should load latest through the safe helper")
    require("load latest model failed" in workflow, "workflow should log latest load failures")
    require('agent.save_model(id="latest")' in workflow, "workflow should save the checkpoint name it later loads")
    require("def _save_latest_model" in workflow, "workflow model saving should be isolated")
    require("_save_latest_model(agent, logger)" in workflow, "workflow should save latest through the safe helper")
    require("save latest model failed" in workflow, "workflow should log checkpoint save failures")
    require("def _send_sample_data" in workflow, "workflow sample sending should be isolated")
    require("_send_sample_data(agent, list(g_data), logger)" in workflow, "workflow should send sample copies through helper")
    require("send sample data failed" in workflow, "workflow should log sample send failures")
    require("agent.send_sample_data(sample_data)" in workflow, "workflow should not clear the list object sent to learner")
    require("def _process_samples" in workflow, "workflow sample processing should be isolated")
    require("_process_samples(collector, logger)" in workflow, "workflow should process samples through the safe helper")
    require("sample process failed" in workflow, "workflow should log sample processing failures")
    require("samples = _process_samples" in workflow, "workflow should avoid yielding failed sample conversions")
    require("def _should_log_progress" in workflow, "workflow should centralize progress log gating")
    require("need_to_predict and predict_cnt > 0 and predict_cnt % 20 == 0" in workflow, "workflow should not log every non-prediction frame")
    require("_should_log_progress(predict_cnt, done, need_to_predict)" in workflow, "workflow should use robust progress log gating")

    require(package_script.exists(), "submission package script is required")
    require(check_script.exists(), "offline check script is required")
    require(package_script.stat().st_mode & 0o111, "submission package script should be executable")
    require(check_script.stat().st_mode & 0o111, "offline check script should be executable")


if __name__ == "__main__":
    main()
